-- A confirmed named participant reserves their own place plus the host-approved
-- party allowance. Pending invitations do not reserve capacity.
create function sontu_private.reserved_party_places(event_id uuid)
returns integer language sql stable security definer set search_path='' as $$
  select coalesce(sum(1 + p.plus_one_allowance),0)::integer
  from sontu_private.event_participants p
  where p.event_instance_id=event_id and p.commitment_state='CONFIRMED'
$$;
revoke all on function sontu_private.reserved_party_places(uuid) from public,anon,authenticated;

create or replace function sontu_private.rsvp_party_allowance(event_id uuid,participant_id uuid,allowance integer)
returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); e sontu_private.event_instances; v sontu_private.event_versions; p sontu_private.event_participants; reserved integer;
begin
  if actor is null or allowance not between 0 and 10 then return sontu_private.fail('INVALID_INPUT'); end if;
  select * into e from sontu_private.event_instances where id=rsvp_party_allowance.event_id and host_owner_user_id=actor and event_kind='SIMPLE' and lifecycle in ('DRAFT','PUBLISHED') for update;
  if not found then return sontu_private.fail('UNAUTHORIZED'); end if;
  select * into p from sontu_private.event_participants where id=participant_id and event_instance_id=e.id for update;
  -- Party seats are an attendance commitment, so only a confirmed invite can
  -- receive them. This avoids holding phantom capacity for unanswered email.
  if p.id is null or p.commitment_state<>'CONFIRMED' then return sontu_private.fail('INVALID_STATE'); end if;
  select * into v from sontu_private.event_versions where event_instance_id=e.id and version_number=e.current_version_number;
  reserved:=sontu_private.reserved_party_places(e.id)-p.plus_one_allowance+allowance;
  if v.capacity is not null and reserved>v.capacity then return sontu_private.fail('CAPACITY_FULL'); end if;
  update sontu_private.event_participants set plus_one_allowance=allowance where id=p.id;
  insert into sontu_private.audit_entries(event_instance_id,actor_ref,audit_kind,metadata)
    values(e.id,actor::text,'party_allowance_changed',jsonb_build_object('participant_id',p.id,'allowance',allowance,'reserved_places',reserved));
  return jsonb_build_object('status','ready','participant_id',participant_id,'plus_one_allowance',allowance,'reserved_places',reserved);
end $$;

create or replace function sontu_private.simple_access(token text default null,event_id uuid default null,decision text default null,expected_version integer default null,operation_id uuid default null) returns jsonb
language plpgsql security definer set search_path='' as $$
declare p sontu_private.event_participants; e sontu_private.event_instances; v sontu_private.event_versions;
 c sontu_private.consequence_cases; rr sontu_private.participant_reconfirmations; oldop sontu_private.operations;
 mail text; fingerprint text; result jsonb; reserved integer;
begin
 mail:=sontu_private.verified_email(); if mail is null then return sontu_private.fail('VERIFY_EMAIL'); end if;
 if decision is not null then if operation_id is null then return sontu_private.fail('INVALID_INPUT'); end if; perform pg_advisory_xact_lock(hashtextextended(operation_id::text,0)); end if;
 select * into p from sontu_private.event_participants ep where ep.invitation_email=mail and ((token is not null and ep.token_hash=sha256(convert_to(token,'UTF8'))) or (token is null and ep.event_instance_id=event_id));
 if not found then return sontu_private.fail('INVITATION_UNAVAILABLE'); end if;
 select * into e from sontu_private.event_instances where id=p.event_instance_id and event_kind='SIMPLE' for update; if not found then return sontu_private.fail('INVITATION_UNAVAILABLE'); end if;
 select * into p from sontu_private.event_participants where id=p.id and invitation_email=mail and token_revoked_at is null and token_expires_at>now() and (token is null or token_hash=sha256(convert_to(token,'UTF8'))); if not found or e.lifecycle='DRAFT' then return sontu_private.fail('INVITATION_UNAVAILABLE'); end if;
 select * into v from sontu_private.event_versions where event_instance_id=e.id and version_number=e.current_version_number;
 select * into c from sontu_private.consequence_cases where event_instance_id=e.id order by created_at desc,id desc limit 1;
 select * into rr from sontu_private.participant_reconfirmations where event_participant_id=p.id and consequence_case_id=c.id;
 reserved:=sontu_private.reserved_party_places(e.id);
 if decision is null then return jsonb_build_object('status','ready','event',jsonb_build_object('id',e.id,'title',v.title,'description',v.description,'starts_at',v.starts_at,'ends_at',v.ends_at,'timezone',v.timezone,'venue_label',v.venue_label,'cover_key',v.cover_key,'lifecycle',e.lifecycle,'current_version',e.current_version_number,'responses_open',e.lifecycle='PUBLISHED' and v.starts_at>now(),'full',v.capacity is not null and reserved>=v.capacity),'participant',jsonb_build_object('display_name',p.display_name,'commitment_state',p.commitment_state,'invitation_state',p.invitation_state,'response',rr.state,'reconfirmation_required',c.disposition in ('OPEN_UNRESOLVED','PENDING_EXTERNAL') and rr.state='AWAITING_RESPONSE')); end if;
 fingerprint:=jsonb_build_object('participant',p.id,'decision',decision,'version',expected_version)::text;
 select * into oldop from sontu_private.operations where id=operation_id; if found then if oldop.actor_ref<>p.id::text or oldop.request_fingerprint<>fingerprint then return sontu_private.fail('IDEMPOTENCY_MISMATCH'); end if; return oldop.result; end if;
 if expected_version is distinct from e.current_version_number then return sontu_private.fail('STALE_CONFLICT'); end if; if e.lifecycle<>'PUBLISHED' or v.starts_at<=now() then return sontu_private.fail('INVALID_STATE'); end if;
 if decision in ('ACCEPT_INVITE','DECLINE_INVITE') then
  if p.commitment_state<>'NO_COMMITMENT' then return sontu_private.fail('INVALID_STATE'); end if;
  if decision='ACCEPT_INVITE' and v.capacity is not null and reserved+1>v.capacity then return sontu_private.fail('CAPACITY_FULL'); end if;
  update sontu_private.event_participants set invitation_state=case when decision='ACCEPT_INVITE' then 'ACCEPTED' else 'DECLINED' end,commitment_state=case when decision='ACCEPT_INVITE' then 'CONFIRMED' else 'NO_COMMITMENT' end where id=p.id;
 elsif decision in ('WITHDRAW','RECONFIRMED','RELEASED_DECLINED') then
  if p.commitment_state<>'CONFIRMED' then return sontu_private.fail('INVALID_STATE'); end if;
  if decision in ('RECONFIRMED','RELEASED_DECLINED') and (rr.id is null or rr.state<>'AWAITING_RESPONSE' or c.disposition not in ('OPEN_UNRESOLVED','PENDING_EXTERNAL')) then return sontu_private.fail('INVALID_STATE'); end if;
  if decision<>'RECONFIRMED' then update sontu_private.event_participants set commitment_state='RELEASED_DECLINED',plus_one_allowance=0 where id=p.id; end if;
  if rr.id is not null and rr.state='AWAITING_RESPONSE' and c.disposition in ('OPEN_UNRESOLVED','PENDING_EXTERNAL') then update sontu_private.participant_reconfirmations set state=case when decision='RECONFIRMED' then decision else 'RELEASED_DECLINED' end,responded_at=now() where id=rr.id; update sontu_private.consequence_cases set row_version=row_version+1,disposition=case when not exists(select 1 from sontu_private.participant_reconfirmations where consequence_case_id=c.id and state='AWAITING_RESPONSE') then 'RESOLVED' else disposition end,resolved_at=case when not exists(select 1 from sontu_private.participant_reconfirmations where consequence_case_id=c.id and state='AWAITING_RESPONSE') then now() else null end where id=c.id; end if;
 else return sontu_private.fail('INVALID_INPUT'); end if;
 insert into sontu_private.evidence_records(event_instance_id,applicable_event_version_id,source_kind,source_ref,external_evidence_id,observed_status,authoritative_at,is_simulated) values(e.id,v.id,'PARTICIPANT',p.id::text,operation_id::text,decision,now(),false);
 result:=jsonb_build_object('status','ready','event_id',e.id,'current_version',e.current_version_number,'operation_id',operation_id);
 insert into sontu_private.operations values(operation_id,p.id::text,'simple_response',e.id,fingerprint,result,now());
 insert into sontu_private.audit_entries(event_instance_id,operation_id,actor_ref,audit_kind,metadata) values(e.id,operation_id,p.id::text,decision,jsonb_build_object('version',e.current_version_number,'verified_user_id',auth.uid())); return result;
end $$;

-- Account RSVP and accountless guest RSVP share the same locked reservation
-- calculation. Each only creates one primary place.
create or replace function sontu_private.public_event_participation(event_id uuid,action text default 'READ',expected_version integer default null,operation_id uuid default null) returns jsonb
language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid(); mail text:=sontu_private.verified_email(); event_row sontu_private.event_instances; version_row sontu_private.event_versions; participant sontu_private.event_participants; prior_operation sontu_private.operations; reserved integer; total_going integer; display text; fingerprint text; result jsonb;
begin
 if actor is null then return sontu_private.fail('UNAUTHORIZED'); end if; if mail is null then return sontu_private.fail('VERIFY_EMAIL'); end if; if action not in ('READ','JOIN','WITHDRAW') or (action<>'READ' and operation_id is null) then return sontu_private.fail('INVALID_INPUT'); end if; if action<>'READ' then perform pg_advisory_xact_lock(hashtextextended(operation_id::text,0)); end if;
 fingerprint:=jsonb_build_object('actor',actor,'event_id',event_id,'action',action,'version',expected_version)::text; if action<>'READ' then select * into prior_operation from sontu_private.operations where id=operation_id; if found then if prior_operation.actor_ref<>actor::text or prior_operation.request_fingerprint<>fingerprint then return sontu_private.fail('IDEMPOTENCY_MISMATCH'); end if; return prior_operation.result; end if; end if;
 select * into event_row from sontu_private.event_instances where id=public_event_participation.event_id and event_kind='SIMPLE' and visibility in ('PUBLIC','UNLISTED') for update; if not found or event_row.lifecycle='DRAFT' then return sontu_private.fail('INVITATION_UNAVAILABLE'); end if; select * into version_row from sontu_private.event_versions where event_instance_id=event_row.id and version_number=event_row.current_version_number; select * into participant from sontu_private.event_participants p where p.event_instance_id=event_row.id and (p.participant_user_id=actor or lower(p.invitation_email)=mail) order by (p.participant_user_id=actor) desc limit 1; reserved:=sontu_private.reserved_party_places(event_row.id); select reserved+1+count(*) into total_going from sontu_private.event_team_members m where m.event_instance_id=event_row.id and m.attends_event;
 if action='READ' then return jsonb_build_object('status','ready','commitment_state',participant.commitment_state,'current_version',event_row.current_version_number,'participant_count',reserved,'going_count',total_going,'capacity',version_row.capacity,'full',version_row.capacity is not null and reserved>=version_row.capacity,'responses_open',event_row.lifecycle='PUBLISHED' and version_row.starts_at>now()); end if; if expected_version is distinct from event_row.current_version_number or event_row.lifecycle<>'PUBLISHED' or version_row.starts_at<=now() or event_row.host_owner_user_id=actor then return sontu_private.fail('INVALID_STATE'); end if;
 if action='JOIN' then if participant.id is not null and participant.commitment_state='CONFIRMED' then result:=jsonb_build_object('status','ready','event_id',event_row.id,'current_version',event_row.current_version_number,'operation_id',operation_id); else if version_row.capacity is not null and reserved+1>version_row.capacity then return sontu_private.fail('CAPACITY_FULL'); end if; select coalesce(nullif(p.display_name,''),p.first_name,split_part(mail,'@',1)) into display from sontu_private.account_profiles p where p.user_id=actor; display:=coalesce(display,split_part(mail,'@',1)); if participant.id is null then insert into sontu_private.event_participants(event_instance_id,display_name,commitment_state,invitation_email,invitation_state,participant_user_id) values(event_row.id,display,'CONFIRMED',mail,null,actor) returning * into participant; else update sontu_private.event_participants set participant_user_id=actor,display_name=display,commitment_state='CONFIRMED',invitation_state=case when invitation_state is null then null else 'ACCEPTED' end where id=participant.id returning * into participant; end if; result:=jsonb_build_object('status','ready','event_id',event_row.id,'current_version',event_row.current_version_number,'operation_id',operation_id); end if; else if participant.id is null or participant.commitment_state<>'CONFIRMED' then return sontu_private.fail('INVALID_STATE'); end if; update sontu_private.event_participants set commitment_state='RELEASED_DECLINED',plus_one_allowance=0 where id=participant.id; result:=jsonb_build_object('status','ready','event_id',event_row.id,'current_version',event_row.current_version_number,'operation_id',operation_id); end if;
 insert into sontu_private.operations(id,actor_ref,command_type,target_id,request_fingerprint,result) values(operation_id,actor::text,lower(action)||'_public_event',event_row.id,fingerprint,result); insert into sontu_private.audit_entries(event_instance_id,operation_id,actor_ref,audit_kind,metadata) values(event_row.id,operation_id,actor::text,lower(action)||'_public_event',jsonb_build_object('version',event_row.current_version_number,'participant_id',participant.id)); return result;
end $$;

create or replace function sontu_private.guest_event_participation(event_id uuid,action text,guest_name text default null,guest_email text default null,expected_version integer default null,operation_id uuid default null,manage_token uuid default null) returns jsonb
language plpgsql security definer set search_path='' as $$
declare e sontu_private.event_instances; v sontu_private.event_versions; p sontu_private.event_participants; oldop sontu_private.operations; reserved integer; normalized_email text:=lower(trim(coalesce(guest_email,''))); normalized_name text:=trim(coalesce(guest_name,'')); fingerprint text; actor_ref text; result jsonb; token_digest bytea:=sha256(convert_to(manage_token::text,'UTF8'));
begin
 if action not in ('READ','JOIN','WITHDRAW') or manage_token is null then return sontu_private.fail('INVALID_INPUT'); end if; if action='JOIN' and (length(normalized_name) not between 1 and 120 or length(normalized_email)>254 or normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$') then return sontu_private.fail('INVALID_INPUT'); end if;
 actor_ref:='guest:'||encode(token_digest,'hex'); if action<>'READ' and operation_id is null then return sontu_private.fail('INVALID_INPUT'); end if; if action<>'READ' then perform pg_advisory_xact_lock(hashtextextended(operation_id::text,0)); end if;
 fingerprint:=jsonb_build_object('event_id',event_id,'action',action,'name',normalized_name,'email',normalized_email,'token',manage_token,'version',expected_version)::text; if action<>'READ' then select * into oldop from sontu_private.operations where id=operation_id; if found then if oldop.actor_ref<>actor_ref or oldop.request_fingerprint<>fingerprint then return sontu_private.fail('IDEMPOTENCY_MISMATCH'); end if; return oldop.result; end if; end if;
 select * into e from sontu_private.event_instances where id=guest_event_participation.event_id and event_kind='SIMPLE' and visibility in ('PUBLIC','UNLISTED') and participation_access='ANYONE' for update; if not found or e.lifecycle='DRAFT' then return sontu_private.fail('INVITATION_UNAVAILABLE'); end if;
 select * into v from sontu_private.event_versions where event_instance_id=e.id and version_number=e.current_version_number; select * into p from sontu_private.event_participants ep where ep.event_instance_id=e.id and (ep.token_hash=token_digest or (ep.guest_recovery_token_hash=token_digest and ep.guest_recovery_token_expires_at>now())) limit 1; reserved:=sontu_private.reserved_party_places(e.id);
 if action='READ' then return jsonb_build_object('status','ready','commitment_state',p.commitment_state,'display_name',p.display_name,'current_version',e.current_version_number,'participant_count',reserved,'capacity',v.capacity,'full',v.capacity is not null and reserved>=v.capacity,'responses_open',e.lifecycle='PUBLISHED' and v.starts_at>now()); end if;
 if expected_version is distinct from e.current_version_number or e.lifecycle<>'PUBLISHED' or v.starts_at<=now() then return sontu_private.fail('INVALID_STATE'); end if;
 if action='JOIN' then if p.id is not null and p.commitment_state='CONFIRMED' then result:=jsonb_build_object('status','ready','commitment_state','CONFIRMED','display_name',p.display_name,'current_version',e.current_version_number); else if p.id is null and exists(select 1 from sontu_private.event_participants ep where ep.event_instance_id=e.id and lower(ep.invitation_email)=normalized_email) then return sontu_private.fail('EMAIL_UNAVAILABLE'); end if; if v.capacity is not null and reserved+1>v.capacity then return sontu_private.fail('CAPACITY_FULL'); end if; if p.id is null then insert into sontu_private.event_participants(event_instance_id,display_name,commitment_state,invitation_email,token_hash,token_expires_at) values(e.id,normalized_name,'CONFIRMED',normalized_email,token_digest,v.ends_at+interval '30 days') returning * into p; else update sontu_private.event_participants set display_name=normalized_name,invitation_email=normalized_email,commitment_state='CONFIRMED' where id=p.id returning * into p; end if; result:=jsonb_build_object('status','ready','commitment_state','CONFIRMED','display_name',p.display_name,'current_version',e.current_version_number); end if; else if p.id is null or p.commitment_state<>'CONFIRMED' then return sontu_private.fail('INVALID_STATE'); end if; update sontu_private.event_participants set commitment_state='RELEASED_DECLINED',plus_one_allowance=0 where id=p.id; result:=jsonb_build_object('status','ready','commitment_state','RELEASED_DECLINED','display_name',p.display_name,'current_version',e.current_version_number); end if;
 insert into sontu_private.operations(id,actor_ref,command_type,target_id,request_fingerprint,result) values(operation_id,actor_ref,lower(action)||'_guest_event',e.id,fingerprint,result); insert into sontu_private.audit_entries(event_instance_id,operation_id,actor_ref,audit_kind,metadata) values(e.id,operation_id,actor_ref,lower(action)||'_guest_event',jsonb_build_object('version',e.current_version_number,'participant_id',p.id)); return result;
end $$;
